### ISSUE TITLE
Dil

### ISSUE THREAD

**Issue by musfay** [murathasev/casper-csd#2]
Casper global bir marka değil ğ tüm depo niye ingilizce

**Comment by halitsever** [comment]
Olması dileğiyle

**Comment by musfay** [comment]
Casper global olsa ne olacak hiçbir parçası yerli değil ki para dönüyor sadece

**Comment by halitsever** [comment]
sus
<img src="https://i.ibb.co/hZTYWTv/Ads-z12.png">
